# Generated by Django 4.2.15 on 2024-08-07 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField()),
                ('upvotes', models.PositiveIntegerField()),
                ('downvotes', models.PositiveBigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('comments', models.CharField()),
            ],
        ),
    ]
